/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example.helloworld

class App {
    val greeting: String get() {
        return "Hello World!"
    }

    var hello: String? = null
//    fun doIt(pair: Pair<String, String>) {
//        println("-> ${pair.first}, ${pair.second} <-")
//        hello = pair.first
//    }
}

fun main() {
    println(App().greeting)

//    App().doIt("Hello" to "World")
}
