/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example.helloworld

class App {
    val greeting: String get() {
        return "Hello World!"
    }

    // a plain member variable
    var hello: String? = null

    // use Kotlin Standard Library:
    fun doIt(pair: Pair<String, String>) {
        println("-> ${pair.first}, ${pair.second} <-")
        hello = pair.first
    }
}

class AppList {
    val someList = listOf(App(),App(),App())
}
fun main() {
    println("Starting app with println()...")
    println()

    // Use Kotlin Standard Library
    val app = App()
    app.hello = "[This is just a test]"
    println(app.hello)
    app.doIt("Hello" to "World")
    println("app.hello = '${app.hello}'")
}
