/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.jvm)

    // Use the current version of Kotlin
    //kotlin("jvm") version "1.9.22"
    id("com.github.johnrengelman.shadow") version "7.0.0"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)

    // kotlin dep
    implementation(kotlin("stdlib"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.helloworld.AppKt"
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "org.example.helloworld.AppKt"
    }
}
